NativeScript/ios

README.md, v8ios.xcodeproj/project.pbxproj
I was having some build errors caused by the older llvm version on my machine as well as missing file references in the pbxproj. Working properly now.
=> Add llvm requirement and missing files to pbxproj

NativeScript/runtime/ClassBuilder.mm, NativeScript/runtime/Metadata.h, NativeScript/runtime/MetadataBuilder.mm, NativeScript/runtime/MetadataInlines.h, NativeScript/runtime/Reference.cpp, TestRunner/app/tests/MetadataTests.js, metadata-generator/build-step-metadata-generator.py, metadata-generator/src/Binary/binarySerializer.cpp, metadata-generator/src/Binary/binaryStructures.cpp, metadata-generator/src/Binary/binaryStructures.h, metadata-generator/src/Binary/binaryTypeEncodingSerializer.cpp, metadata-generator/src/Binary/binaryWriter.h, metadata-generator/src/Binary/metaFile.cpp, metadata-generator/src/Binary/metaFile.h, metadata-generator/src/HeadersParser/Parser.cpp, metadata-generator/src/Meta/DeclarationConverterVisitor.h, metadata-generator/src/Meta/Filters/ModulesBlacklist.h, metadata-generator/src/Meta/MetaEntities.h, metadata-generator/src/Meta/MetaFactory.cpp, metadata-generator/src/TypeScript/DefinitionWriter.cpp, metadata-generator/src/Yaml/MetaYamlTraits.h, metadata-generator/src/main.cpp
The Objective-C runtime doesn't behave consistently with Swift class
names. Sometimes the mangled name can only be used, other times
the demangled one. To avoid hardcoding any logic which may get
easily broken in the future, we are adding both names in the global
tables and using the mangled name in signatures.
Observation which lead to this change:
* `objc_getClass(const char *)` - accepts both mangled and demangled
names of Swift classes which are not nested in another class. Nested
classes however can be discovered only by their mangled name.
* `class_getName` - returns the demangled name for Swift classes
which aren't nested, and the mangled one for nested.
* On Mac Catalyst `class_getName` returns  the mangled names
no matter whether the class is nested or not.
=> fix: Register Swift classes with both native names

NativeScript/runtime/Constants.cpp, NativeScript/runtime/Constants.h, NativeScript/runtime/Interop.mm, NativeScript/runtime/MetadataBuilder.mm, v8ios.xcodeproj/project.pbxproj
Fixes #34 in which we have a collision with an existing method name for `UINavigationController.__viewWillappear:` and which results in the following errors to be logged when starting up an application:
```
Unbalanced calls to begin/end appearance transitions for <UINavigationControllerImpl: 0x7ff555057200>
```
The application might crash as a result of this.
=> fix: Use better swizzled methods prefix to avoid collisions with possible existing methods in the class hierarchy

NativeScript/runtime/ArgConverter.mm, NativeScript/runtime/Caches.cpp, NativeScript/runtime/Caches.h, NativeScript/runtime/Runtime.mm, NativeScript/runtime/Worker.mm
Avoid double cache cleanup upon process exit.
Related to #51.
=> fix: Runtime cleanup #51

NativeScript/runtime/ArgConverter.mm, NativeScript/runtime/ClassBuilder.mm, NativeScript/runtime/Runtime.h, NativeScript/runtime/Runtime.mm, TestRunner/app/tests/shared/Workers/index.js
Related to #63.
Steps to reproduce:
```javascript
var worker = new Worker("./tests/shared/Workers/EvalWorker.js");
worker.onmessage = (msg) => {
worker.terminate();
NSNotificationCenter.defaultCenter.postNotificationNameObject("MyNotification", null);
};
const workerScript = `
var NotificationObserver = /** @class */ (function (_super) {
__extends(NotificationObserver, _super);
function NotificationObserver() {
return _super !== null && _super.apply(this, arguments) || this;
}
NotificationObserver.initWithCallback = function (onReceiveCallback) {
var observer = _super.new.call(this);
observer._onReceiveCallback = onReceiveCallback;
return observer;
};
NotificationObserver.prototype.onReceive = function (notification) {
this._onReceiveCallback(notification);
}; …
```
=> fix: Ensure Isolate is alive before using it (#63)

NativeScript/inspector/src/inspector/v8-stack-trace-impl.cc, NativeScript/inspector/utils.h, metadata-generator/src/Meta/Filters/ResolveGlobalNamesCollisionsFilter.h, package.json, project-template/internal/nativescript-build.xcconfig
This has the full change set to build under XCode 12.01 with LLVM 8.01
=> chore: 7.0.2-RC.1 changes

NativeScript/runtime/ArgConverter.h, NativeScript/runtime/ArgConverter.mm, NativeScript/runtime/Caches.h, NativeScript/runtime/Interop.h, NativeScript/runtime/Interop.mm, NativeScript/runtime/MetadataBuilder.h, NativeScript/runtime/MetadataBuilder.mm, TestFixtures/Api/TNSPseudoDataTypes.h, TestFixtures/Api/TNSPseudoDataTypes.m, TestRunner/app/tests/ApiTests.js
Related to #67 
This PR addresses an issue where we replace the existing object prototype with additional protocols returned from pseudo types. Instead of modifying the prototype chain, we build an entirely new chain containing the additional protocols.
=> fix: Do not update in-place object prototypes (#67)

NativeScript/runtime/Caches.h, NativeScript/runtime/DataWrapper.h, NativeScript/runtime/Interop.h, NativeScript/runtime/Interop.mm, NativeScript/runtime/MetadataBuilder.mm, NativeScript/runtime/ObjectManager.mm, NativeScript/runtime/UnmanagedType.h, NativeScript/runtime/UnmanagedType.mm, TestRunner/app/tests/ApiTests.js, v8ios.xcodeproj/project.pbxproj
Related to #54
With this PR we add support for the [Unmanaged](https://developer.apple.com/documentation/swift/unmanaged) structure in the runtime.
=> feat: Support the Unmanaged type (#54)

NativeScript/runtime/Helpers.h, NativeScript/runtime/Helpers.mm, NativeScript/runtime/ModuleInternal.mm
This PR creates a custom version of the code that will loads the JS modules (i.e. require(module)).   By not creating extra buffers and extra memory usage, this speeds up the loading of JS files by ~16%.
=> feat: Faster loading of JS files

NativeScript/runtime/Interop.mm
Related to #77 
- Use proper isolate when creating the handle scope in the block destructor
=> fix: create handle scope with proper isolate (#77)

project-template/internal/nativescript-build.xcconfig
https://github.com/NativeScript/ios-runtime/pull/1289/files
Xcode 12.3 builds succeed when VALIDATE_WORKSPACE is explicitly set to YES.
=> fix(xcode): 12.3 support

NativeScript/runtime/DictionaryAdapter.mm, NativeScript/runtime/PromiseProxy.cpp
Fixes https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/1728, which seems to have been due to thread switching in the callback at [FIRFunctions.m#L187](https://github.com/firebase/firebase-ios-sdk/blob/62735099d51778e43f15adc8f0057b7c8d72e17b/Functions/FirebaseFunctions/FIRFunctions.m#L187). This issue will affect any native library functions called with a JavaScript object which are then wrapped in a DictionaryAdapter, and then attempt to access or enumerate the DictionaryAdapters contents from another thread.
I have not worked in Objective C nor with V8 internals before. This pull request needs a careful review and testing. Thank you @darind for pointing me in the right direction.
=> fix: DictionaryAdapter missing handle scopes and locks

README.md
The current README for attaching the runtime to an existing project works only if you are using a simulator to debug.  For some reason when using a real device Xcode requires you to explicitly add `Nativescript.framework` on the General Tab.
=> chore: Add step to fix attaching to real device

NativeScript/runtime/DictionaryAdapter.mm
DictionaryAdapter is leaking memory when objects are deallocated.
This PR serves to clean up some hanging references. In my test case this reduced the total leaks caused by DictionaryAdapter by 36%.
=> DictionaryAdapter Hanging References

NativeScript/runtime/DictionaryAdapter.mm
Fixes a crash when self->enumerator_ is not set
=> Only clear when set

NativeScript/runtime/Interop.h, NativeScript/runtime/Interop.mm, TestFixtures/Marshalling/TNSPrimitives.h, TestFixtures/Marshalling/TNSPrimitives.m, TestRunner/app/tests/Marshalling/Primitives/Instance.js, TestRunner/app/tests/Marshalling/Primitives/Static.js
fixes: https://github.com/NativeScript/NativeScript/issues/9429
fixes: https://github.com/NativeScript/nativescript-ui-charts/issues/17
=> fix: boolean to NSNumber marshalling

NativeScript/runtime/ClassBuilder.mm
fixes #109.
I was having the same issue as #109 when trying to fix a call to `UISaveVideoAtPathToSavedPhotosAlbum`.  It turns out the runtime would throw an error as soon as you added a method that had a parameter of type interop.Pointer to the ObjCExposedMethods object because GetTypeEncodingType didn't know how to deal with it.
This change also helps fix some of the underlying issues in https://github.com/nstudio/nativescript-plugins/issues/12
=> fix: handle methods with pointer type params

NativeScript/runtime/MetadataBuilder.mm
- Ensure that a static method is not already defined before attempting to set it.
=> fix: Check if a static method is already set

NativeScript/runtime/Interop.mm, NativeScript/runtime/OneByteStringResource.cpp, NativeScript/runtime/OneByteStringResource.h, v8ios.xcodeproj/project.pbxproj
This PR addresses a memory leak when marshalling C string parameters. When a JS string needs to be passed to a native function as a C string parameter, we externalise the backing pointer from the V8 heap to ensure a pinned memory location. 
The underlying buffer will be disposed when the corresponding JS value is GCed
=> fix: Memory leak when marshalling C strings parameters

NativeScript/runtime/Interop.mm
- Take into account null terminated C strings when marshalling parameters to native functions
Related to #131
=> fix: Take into account null terminated C strings (#131)

NativeScript/runtime/ClassBuilder.mm, NativeScript/runtime/InteropTypes.mm
I don't believe this is the definite fix. The correct fix would be for each TypeEncoding type to initialize it's own struct with the proper values instead of relying on them to be "0" or "nil".
Other places that use `PtrTo<>` should be investigated as well as they might contain garbage data ocasionally
=> fix: TypeEncoding might be initialized with random data

NativeScript/runtime/ModuleInternal.mm
solves a leak on first app execution where it builds the code cache and leaks it.
=> fix: don't leak code cache data

NativeScript/runtime/NativeScriptException.mm, NativeScript/runtime/Runtime.mm
This PR aims to address some unwanted crashes that would happen during the `OnUncaughtError` handler.
The first relates to how the `AppPackageJson` file was being read to fetch the `discardUncaughtJsExceptions` flag. The NSJSONSerialization would produce a NSDictionary that would get autoreleased. On subsequent calls to `OnUncaughtError`, the `AppPackageJson` pointer would be cleared causing a bad access.
To address this, I alloc and init a new NSDictionary from the serialization so that this dictionary will not get released between calls to `OnUncaughtError`. I'm not super familiar with Objective-C or how this runtime is setup, so I don't know if there is a point where we _should_ manually release this dictionary. Please let me know if this should be handled.
Second, I ran into an …
=> fix: prevent crashes during onuncaughterror

NativeScript/inspector/JsV8InspectorClient.mm
this fixes a bug where we don't lock the isolate before calling handle_scope, which might make v8 crash.
This crash always happens if you use --debug-brk and try to attach the dev tools
=> fix: lock isolate before handle_scope

metadata-generator/build-step-metadata-generator.py
=> feat: support Xcode 13.3 and iOS 15.4

NativeScript/inspector/InspectorServer.mm, NativeScript/inspector/JsV8InspectorClient.h, NativeScript/inspector/JsV8InspectorClient.mm
also adds a nice semaphore so we convert a busy wait into a more CPU friendly one
=> fix(inspector): ensure socket message is copied and stored

v8.patch
This fixes the broken parts of the patch so that it can be applied to 01621b70b2fedd756470a79ad1e6cfdc9ba28b49
=> fix: v8 9.2.230.18 patch

NativeScript/runtime/ArrayAdapter.mm, NativeScript/runtime/DictionaryAdapter.mm, NativeScript/runtime/NSDataAdapter.mm
It was used Xcode instrumentals to identify the leaks and test the fixes.
=> fix: memory leak on ArrayAdapter, DictionaryAdapter and NSDataAdapter

NativeScript/runtime/Helpers.h, NativeScript/runtime/Helpers.mm
The actual reasons still need to be added, but this should be enough to slowly start adding information to the magical "assertion failed" errors with no description of what failed and why
=> feat: add support for reasons on assertion failure

.gitignore, NativeScript/NativeScript-Prefix.pch, NativeScript/runtime/Helpers.h, NativeScript/runtime/Helpers.mm, NativeScript/runtime/Interop.h, NativeScript/runtime/Interop.mm, package.json
Checking if a swizzled method exists constructs the selector for every call by concatenating the swizzle prefix to the actual selector string. This is pretty slow when doing many calls. 
This PR keeps a map (using robin_hood::unordered_map for performance) of SEL (selector) pairs, so that the swizzled selector is only constructed once, and any subsequent calls will use the fast-path by returning the value from the cache.
From a few performance tests, we've seen a ~30% improvement, though it may vary from case to case.
=> perf: cache swizzled selector construction

NativeScript/runtime/Console.cpp
removed in fea46b282213e6557a0f0b80322b1694104676c1 then partially restored in 19d56eb55f4e0ce8756b2ba63c8f2ddae2a84943
=> fix: console prefix missing

metadata-generator/src/TypeScript/DefinitionWriter.cpp
before:
```ts
interface __darwin_fp_control {
__invalid: number;
__denorm: number;
__zdiv: number;
__ovrfl: number;
__undfl: number;
__precis: number;
: number;
__pc: number;
__rc: number;
: number;
: number;
}
```
after:
```ts
interface __darwin_fp_control {
__invalid: number;
__denorm: number;
__zdiv: number;
__ovrfl: number;
__undfl: number;
__precis: number;
__pc: number;
__rc: number;
}
```
=> fix(metadata-generator): skip empty bitfields

NativeScript/NativeScript-Prefix.pch, NativeScript/runtime/ExtVector.cpp, NativeScript/runtime/Metadata.mm, NativeScript/runtime/Pointer.cpp, NativeScript/runtime/Reference.cpp, package.json
ios16 beta 5 crashes on boot with a trace somewhat similar to the one below. Adding a try/catch around `MethodMeta::isImplementedInClass` seems to catch the error, but ideally, we should figure out what caused the change in behavior.
The methods where it errors caught through the debugger (`po this->jsName()`):
```
attemptRecoveryFromErrorOptionIndex
attemptRecoveryFromErrorOptionIndexDelegateDidRecoverSelectorContextInfo
fileManagerShouldProceedAfterError
fileManagerWillProcessPath
provideImageDataBytesPerRowOriginSizeUserInfo
```
```
+[__NSCFType allocWithZone:]: unrecognized selector sent to class 0x7ff863b44f30
```
```
0   CoreFoundation                	    0x7ff800427370 __exceptionPreprocess + 226
1   libobjc.A.dylib               	    0x7ff80004dbaf objc_exception_throw + 48
2 …
```
=> fix(ios16-beta5): errors and crash

NativeScript/inspector/JsV8InspectorClient.mm, NativeScript/runtime/ArgConverter.mm, NativeScript/runtime/ClassBuilder.mm, NativeScript/runtime/ExtVector.cpp, NativeScript/runtime/InteropTypes.mm, NativeScript/runtime/MetadataBuilder.mm, NativeScript/runtime/Reference.cpp
use fast primitive setters & fast js primitive setters
=> chore: perf op

NativeScript/runtime/ArcMacro.h, NativeScript/runtime/Helpers.h, v8ios.xcodeproj/project.pbxproj
Helpers.h is being used by non-ARC libs interally, which means we need `autorelease` on them.
Added ArcMacro.h to help handling cases like this in the future.
=> fix: memory leak on new string handling

NativeScript/runtime/PromiseProxy.cpp
This will cleanup references to `resolve` and `reject` after they're called once.
I'm not sure if this will solve the issue for never resolving promises, but in my tests it resolved the issues in `@nativescript/core` where ImageSource would leak after loading an image from a url.
To go deeper into the issue, this happened because the promise would keep a reference to PromiseProxy's resolve/reject functions, which started to become a problem when this function would then add a native callback, which would keep a reference to the full context, keeping the resolve/reject always in memory (and usually also the promise itself).
Ultimately this created a circular reference with the `reactions_or_result` GC root that didn't go away until we removed the reference to the original resove/reject …
=> fix: resolve PromiseProxy context memory leak

NativeScript/runtime/ArgConverter.mm, TestFixtures/Marshalling/TNSObjCTypes.h, TestFixtures/Marshalling/TNSObjCTypes.m, TestRunner/app/tests/ApiTests.js, TestRunner/app/tests/index.js
Fixes issue by the `[]` array access returning the wrong (parent) object. The bug was introduced by this change: https://github.com/NativeScript/ios/commit/fa44007f9aab12b277836f4388861066837ef14c#diff-65a98e0ce763ac29ef9ed8dd75b8b8d92447c04ffc1bfb5df78f5d33b67e2091L865-R873
Added a test case verifying this scenario.
Note: commented out MatrixTests as this has been failing on main with recent XCode versions. We should fix the matrix helpers.
=> fix: incorrect wrapper in indexed array access

NativeScript/v8runtime/V8Runtime.h, README.md, v8ios.xcodeproj/project.pbxproj
- Removes a couple of leftovers from using external startup data, which is no longer supported as per NativeScript/NativeScript#8926. No need to update V8 libraries as they are already built for iOS with `v8_use_external_startup_data=false`.
- Readme improvement that I had sitting around on my local checkout.
=> Remove defunct V8 external startup data stuff

NativeScript/runtime/Caches.h, NativeScript/runtime/Helpers.h, NativeScript/runtime/Helpers.mm, NativeScript/runtime/ModuleBinding.cpp, NativeScript/runtime/ModuleBinding.hpp, NativeScript/runtime/Runtime.mm, NativeScript/runtime/Worker.h, NativeScript/runtime/Worker.mm, v8ios.xcodeproj/project.pbxproj
Draft on how new modules and globals could work
Instead of calling Init manually on the runtime, each module would register itself either as a global (`NODE_BINDING_PER_ISOLATE_INIT_OBJ`) or as a node module (`NODE_BINDING_CONTEXT_AWARE_INTERNAL`).
Globals are already working, we still need work for the node modules (essentially check if a module is a native module and call it + cache it).
This will allow us to `require('ns:crypto')`, for example. In the future, we could even rework the way we use native libraries so you can do: `import { NSString } from 'ns:native:Foundation'` to get a slimmer app size and automatic metadata filtering through bundlers
https://github.com/NativeScript/NativeScript/issues/195
=> feat: use node logic for globals and modules

NativeScript/runtime/ModuleBinding.hpp, NativeScript/runtime/Timers.cpp, NativeScript/runtime/Timers.hpp, TestRunner/app/tests/Timers.js, TestRunner/app/tests/index.js, v8ios.xcodeproj/project.pbxproj
Uses https://github.com/NativeScript/ios/pull/215
There's about a 3-4x speed improvement on timers and they're extremely memory efficient now.
=> feat: add native timers

NativeScript/runtime/Caches.cpp, NativeScript/runtime/Caches.h, NativeScript/runtime/GCProtectedSet.cpp, NativeScript/runtime/GCProtectedSet.h, NativeScript/runtime/Runtime.mm, v8ios.xcodeproj/project.pbxproj
Assuming all GCProtected wrappers are tracked within Caches, this should ensure that their JS object and the cppgc wrapper itself are not collected (or are at least continued to be traced), until the bit is released.
This is done by allocating a dummy object and storing it on the global object of a runtime, which when traced, performs a trace of every object known to its local Caches instance.
=> Add mechanism for tracing wrappers with GCProtected set

NativeScript/runtime/Interop.mm, TestFixtures/Marshalling/TNSObjCTypes.h, TestFixtures/Marshalling/TNSObjCTypes.m, TestRunner/app/tests/Marshalling/ObjCTypesTests.js
This is a pretty big change and it affects all blocks, so needs to be carefully tested.
I added 2 unit tests to blocks to ensure they're retained and released accordingly (they currently fail without my changes)
=> fix: prevent JS function to native block leak

NativeScript/runtime/ArgConverter.mm, NativeScript/runtime/ArrayAdapter.mm, NativeScript/runtime/ClassBuilder.mm, NativeScript/runtime/DictionaryAdapter.mm, NativeScript/runtime/Interop.mm, NativeScript/runtime/IsolateWrapper.cpp, NativeScript/runtime/IsolateWrapper.h, NativeScript/runtime/NSDataAdapter.mm, NativeScript/runtime/Runtime.mm, NativeScript/runtime/Timers.cpp, v8ios.xcodeproj/project.pbxproj
Release adapter ownership back to ARC once we set it.
=> fix: bridge release adapters

NativeScript/runtime/Interop.h, NativeScript/runtime/InteropTypes.mm, TestRunner/app/tests/Marshalling/ReferenceTests.js
adds a new interop function `function interop.stringFromCstring(ptr: interop.Pointer | interop.Reference, length?: number): string` which allows you to easily convert a char* into a JS string (around 10x faster than doing `NSString.stringWithUTF8String().toString()`)
=> feat: add interop.stringFromCString

metadata-generator/build-step-metadata-generator.py, project-template/internal/nsld.sh
`nsld.sh` is usually invoked per target architecture.
Right now, we generate metadata for all valid architectures from `env[ARCH]`. This can cause issues in case we run mutiple builds in parallel (one for each target architecture) in which case both metadata generators output to the same files likely causing file corruption.
With these changes, in case a first argument is passed to the metadata generator python script, we skip architectures that don't match the argument.
This way, in case the metadata generation is invoked via nsld - we pass through the target architecture.
=> fix: only generate metadata for the targeted arch

README.md
`TNSLiveSync` seems outdated and needed to replaced with `TKLiveSync`. Also, it was necessary to re-add `TKLiveSync.framework` from `v8ios` package, at least in order to make it work on a physical device.
It would probably good to replace the second screenshot so it highlights `TKLiveSync.framework` as well.
=> Fix instructions for attaching the runtime to a NativeScript app

metadata-generator/build-step-metadata-generator.py
This stems from my work on a plugin that uses the SDWebImage package. Metadata for some classes were not getting generated when building for a physical device. 
This will probably also resolve #245 since they were also running into problems with the same SDWebImage package.
=> fix: Xcode 15.3+ not setting TARGET_OS_IOS correctly

project-template-ios/internal/Swift-ObjC-Bridging-Header.h
This commit aims to fix this issue reported here: https://github.com/NativeScript/ios/issues/249
I don't know if this is the best solution, but as we don't need NS headers at WatchOS development, I think we can disable it for the target `TARGET_OS_WATCH`.
=> fix(ios): Fix broken build of WatchOS embedded apps

metadata-generator/src/Meta/MetaEntities.h, metadata-generator/src/TypeScript/DocSetManager.cpp, metadata-generator/src/TypeScript/DocSetManager.h
This adds deprecation and since notices to APIs:
Before:
```
widgetMaximumSizeForDisplayMode(displayMode: NCWidgetDisplayMode): CGSize;
```
After:
```
/**
* @since 10.0
* @deprecated 14.0
*/
widgetMaximumSizeForDisplayMode(displayMode: NCWidgetDisplayMode): CGSize;
```
=> feat: add `@deprecation` and `@since` docs

metadata-generator/src/TypeScript/DefinitionWriter.cpp
**This is a possible breaking change**
This adds additional information to native types that expect some kind of protocol.
```
@protocol Option                                                                                
-(NSString *) optionId;                                 
-(NSString *) type;                    
@end                                      
typedef NSObject<Option> Option; 
@protocol Info                                                                                 
-(NSArray<NSObject<Option> *> *) getOptions;
-(NSObject<Option> *) getOption;
@end
typedef NSObject<Info> Info;
```
Generated:
```
interface Option {                                      
optionId(): string;                             
type(): string;                                 
} …
```
=> feat: add protocol information to native types

.clang-format, .clang-format-ignore, .husky/pre-commit, README.md, package.json, update_version.sh
uses clang-format to format all files according to the same styling that V8 uses.
We should consider doing this only after the pending PRs we have are merged (including the parallel branches we have with newer V8 versions)
=> chore: use clang-format

NativeScript/runtime/URLImpl.cpp, TestRunner/app/tests/URL.js
Fixes https://github.com/NativeScript/NativeScript/issues/10232#issuecomment-2407096597
=> fix(URL): allow undefined 2nd args and fix pathname return value

NativeScript/runtime/Runtime.h, NativeScript/runtime/Runtime.mm, TestRunner/app/tests/RuntimeImplementedAPIs.js
=> feat: use monotonic time for performance object

NativeScript/ada/ada.cpp, NativeScript/ada/ada.h
=> feat: Ada 3.1.3

NativeScript/runtime/FFICall.h, NativeScript/runtime/Timers.cpp
Fixes the mac catalyst build when using Xcode 16.4. The following errors are now resolved:
```
NativeScript/runtime/Timers.cpp:166:27: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
166 |         Local<Value> argv[argc];
```
```
NativeScript/runtime/FFICall.h:46:62: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
46 |             this->StackSize = malloc_good_size(sizeof(void* [argsCount]));
```
=> fix(catalyst): variable-length arrays

NativeScript/runtime/SymbolLoader.mm
Right now the symbol loader will just log to terminal certain processed paths that are not indicative of a functional issue:
```
NativeScript could not load bundle file:///Library/Developer/CoreSimulator/Volumes/iOS_22B81/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%2018.1.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/UIUtilities.framework
```
These will no longer cloud the terminal output which can cause confusion.
=> fix: symbol loader log true errors only to not confuse terminal output
